language: bash

sudo: required

services:
  - docker

env:
#   Debian
  - OS_SUITE=alpine NGINX_SUITE=mainline VERSION=1.15.12
  - OS_SUITE=alpine NGINX_SUITE=stable VERSION=1.16.0
#   Ubuntu
  - OS_SUITE=xenial NGINX_SUITE=mainline VERSION=1.15.12
  - OS_SUITE=xenial NGINX_SUITE=stable VERSION=1.16.0

before_install:
  - export DOCKER_COMPOSE_VERSION=1.24.0
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - env | sort
  - cd "$OS_SUITE"
  - image="larvacent/nginx:${VERSION}-${OS_SUITE}"

script:
  - travis_retry docker build --build-arg NGINX_VERSION=${VERSION} -t "$image" .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login --username="${DOCKER_REGISTRY_USER}" --password="${DOCKER_REGISTRY_PASSWORD}";
      docker push $image;
      docker tag $image larvacent/nginx:${VERSION};
      docker push larvacent/nginx:${VERSION};
      if [[ "${VERSION}" == "1.15.12" && "${OS_SUITE}" == "alpine" ]]; then
        docker tag $image larvacent/nginx:1.15;
        docker push larvacent/nginx:1.15;
        docker tag $image larvacent/nginx:latest;
        docker push larvacent/nginx:latest;
        docker tag $image larvacent/nginx:mainline;
        docker push larvacent/nginx:mainline;
      fi;
      if [[ "${VERSION}" == "1.14.2" && "${OS_SUITE}" == "alpine" ]]; then
        docker tag $image larvacent/nginx:stable;
        docker push larvacent/nginx:stable;
        docker tag $image larvacent/nginx:1.14;
        docker push larvacent/nginx:1.14;
      fi;
    fi;

# vim:set et ts=2 sw=2:
